### ISSUE TITLE
WoGModifier Cannot Open

### ISSUE THREAD

**Issue by MayBeSuper** [Mygod/WoGCorpProjects#1]
系统:Windows 7
NET Framework 版本:
Microsoft .NET Framework 4 Client Profile
Microsoft .NET Framework 4 Extended
刚进就闪退，系统报错信息如下。
问题签名:
  问题事件名称:   CLR20r3
  问题签名 01:  wogmodifier.exe
  问题签名 02:  4.0.43.275
  问题签名 03:  54546bcf
  问题签名 04:  mscorlib
  问题签名 05:  4.0.0.0
  问题签名 06:  53b50a71
  问题签名 07:  11fe
  问题签名 08:  9d
  问题签名 09:  System.TypeInitialization
  OS 版本:    6.1.7601.2.1.0.256.1
  区域设置 ID:  2052
  其他信息 1:   0a9e
  其他信息 2:   0a9e372d3b4ad19135b953a78882e789
  其他信息 3:   0a9e
  其他信息 4:   0a9e372d3b4ad19135b953a78882e789

**Comment by Mygod** [comment]
此版本需要安装 .NET Framework 4.5.1。
